############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Guide"
url = "guide/"
weight = 6

[[main]]
name = "Blog"
url = "blog/"
weight = 7

# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Guide"
url = "guide/"
weight = 2

[[footer]]
name = "Blog"
url = "blog/"
weight = 3

[[footer]]
name = "Contatti"
url = "contatti/"
weight = 4
